name: silatif
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.4
  image_picker: 0.8.6
  sp_util: 2.0.3
  material_design_icons_flutter: 6.0.7096
  location: 4.4.0
  geolocator: 9.0.2
  intl: ^0.18.0
  loading_animation_widget: ^1.2.0+4
  shimmer: ^3.0.0
  flutter_slidable: ^3.0.0
  dotted_border: ^2.0.0+3
  cached_network_image: ^3.2.3
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4
  firebase_auth: ^4.7.2
  google_fonts: 5.1.0
  flutter:
    sdk: flutter
  step_progress_indicator: ^1.0.2
  swipable_stack: ^2.0.0
  appinio_swiper: ^2.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true
