// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkxzIPrRHkBhBGypyZyphnWkMZXO9kSQU',
    appId: '1:162530700482:web:141ec6c90e543edb571f5b',
    messagingSenderId: '162530700482',
    projectId: 'silatif-c3dba',
    authDomain: 'silatif-c3dba.firebaseapp.com',
    storageBucket: 'silatif-c3dba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkRmbAmKJARheqmiEbAiwvhCkALI5xBAc',
    appId: '1:162530700482:android:1d245d44da253853571f5b',
    messagingSenderId: '162530700482',
    projectId: 'silatif-c3dba',
    storageBucket: 'silatif-c3dba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwy-IQl-vODg6beZjf9fJZgYwXAh1W47A',
    appId: '1:162530700482:ios:321bcfb1dd5e9063571f5b',
    messagingSenderId: '162530700482',
    projectId: 'silatif-c3dba',
    storageBucket: 'silatif-c3dba.appspot.com',
    iosClientId: '162530700482-3o7j91j16qu6pm57kesm7k12le32uiu9.apps.googleusercontent.com',
    iosBundleId: 'com.silatif.startsheep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwy-IQl-vODg6beZjf9fJZgYwXAh1W47A',
    appId: '1:162530700482:ios:321bcfb1dd5e9063571f5b',
    messagingSenderId: '162530700482',
    projectId: 'silatif-c3dba',
    storageBucket: 'silatif-c3dba.appspot.com',
    iosClientId: '162530700482-3o7j91j16qu6pm57kesm7k12le32uiu9.apps.googleusercontent.com',
    iosBundleId: 'com.silatif.startsheep',
  );
}
